version: '3.8'
services:
  gateway:
    build: ./gateway
    restart: always
    hostname: gateway
    environment:
      - PORT=${GATEWAY_PORT}
      - AUTH_SERVICE_HOST=${GATEWAY_AUTH_HOST}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
      - ACCOUNT_SERVICE_HOST=${GATEWAY_ACCOUNT_HOST}
      - ACCOUNT_SERVICE_PORT=${ACCOUNT_SERVICE_PORT}
    ports:
      - 3000:3000
    networks:
      - backend
      - frontend
  authentication:
    build: ./authentication
    restart: always
    hostname: authentication
    environment:
      - TYPEORM_HOST=${POSTGRES_HOST}
      - TYPEORM_PORT=${POSTGRES_PORT}
      - TYPEORM_USERNAME=${POSTGRES_USERNAME}
      - TYPEORM_PASSWORD=${POSTGRES_PASSWORD}
      - TYPEORM_DATABASE=${AUTH_POSTGRES_DATABASE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DATABASE=${REDIS_DATABASE}
      - AUTH_SERVICE_HOST=${AUTH_SERVICE_HOST}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    networks:
      - backend
    links:
      - database
      - cache
  account:
    build: ./account
    restart: always
    hostname: account
    environment:
      - TYPEORM_HOST=${POSTGRES_HOST}
      - TYPEORM_PORT=${POSTGRES_PORT}
      - TYPEORM_USERNAME=${POSTGRES_USERNAME}
      - TYPEORM_PASSWORD=${POSTGRES_PASSWORD}
      - TYPEORM_DATABASE=${ACCOUNT_POSTGRES_DATABASE}
      - ACCOUNT_SERVICE_HOST=${ACCOUNT_SERVICE_HOST}
      - ACCOUNT_SERVICE_PORT=${ACCOUNT_SERVICE_PORT}
    networks:
      - backend
    links:
      - database
  database:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - backend
  cache:
    image: 'redis:latest'
    restart: always
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DATABASE=${REDIS_DATABASE}
    ports:
      - 6379:6379
    networks:
      - backend
networks:
  backend:
    driver: bridge
  frontend:
    name: infrastructure